### ISSUE TITLE
support for multiple jenkins instances

### ISSUE THREAD

**Issue by ssbarnea** [bregman-arie/jino#1]
I think that supporting multiple jenkins instances from start would be critical because of the current jenkins architecture limitations: ~500 jobs/master (yes you can run 1000 but you probably do not wish for that kind of experience).

**Comment by bregman-arie** [comment]
Done.
You can now specify multiple Jenkins instances in jino.conf:

[jenkins/OpenDaylight]
url = ...
[jenkins/RDO]
url = ...
user = ...
password = ...
